#!/bin/bash

# ======================= nvim and packer
#
#

if ! command -v nvim; 
then 
	echo "[X] nvim not installed"
	echo "[+] installing nvim"
	subto apt install neovim

else
	echo "[O] nvim installed"
fi

pathTo_nvimPacker="$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim"

if [ ! -d "$pathTo_nvimPacker" ]; 
then 
	echo "[X] the packer is not installed"
	echo "[+] currently installing"
	
	git clone --depth 1 https://github.com/wbthomason/packer.nvim "$pathTo_nvimPacker"
else
	echo "[O] the packer is successfully installed"
fi


# ========================= languages
#
#

compilerList=(g++ python3 rustc ruby )

for compiler in ${compilerList[@]}; 
do
	if ! command -v "$compiler" ;
	then
		echo "[X] $compiler not installed"
		echo "[+] adding $compiler" 
		sudo apt install "$compiler"

	fi

	if command -v "$compiler" ;
	then 
		echo "[O] $compiler installed"
	else
		echo "[X] $compiler not installed"
	fi
done

# ======================= menu
#
#

languageOptions=("cpp" "python" "rust" "ruby")
chosen=""

# displays options
#
for lang in "${languageOptions[@]}"; do
	echo "$lang"
	echo
done

# picks options
#
while true; 
do
	read -p "your choice" chos
	
	case "$chos" in
		"cpp" ) chosen="cpp";break;;
		"python" ) chosen="python";break;;
		"rust" ) chosen="rust";break;;
		"ruby" ) chosen="ruby";break;;
		*) echo "invalid option";;
	esac
done

LanguagePath_open="./branch_out_folder/$chosen"

# starts language-specific project folder
#




